SELECT R1.FOOD_TYPE, R1.REST_ID, R1.REST_NAME, R1.FAVORITES
FROM REST_INFO R1
WHERE R1.FAVORITES = (
    SELECT MAX(R2.FAVORITES) 
    FROM REST_INFO R2 
    WHERE R1.FOOD_TYPE = R2.FOOD_TYPE
)
ORDER BY R1.FOOD_TYPE DESC;
