# -- 코드를 입력하세요
# SELECT inf.REST_ID, inf.REST_NAME, inf.FOOD_TYPE, inf.FAVORITES, inf.ADDRESS, ROUND(AVG(rev.REVIEW_SCORE),2) AS SCORE
# FROM REST_INFO inf
# JOIN REST_REVIEW rev ON inf.REST_ID = rev.REST_ID
# WHERE inf.ADDRESS LIKE '서울%'
# GROUP BY inf.REST_ID
# ORDER BY SCORE DESC, FAVORITES DESC;


SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, 
ROUND(AVG(B.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS A
JOIN REST_REVIEW AS B
ON A.REST_ID = B.REST_ID
WHERE A.ADDRESS LIKE '서울%'
GROUP BY A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS
ORDER BY SCORE DESC, A.FAVORITES DESC;