-- 코드를 입력하세요
WITH DISCOUNT AS (
    SELECT history.HISTORY_ID, car.CAR_ID, car.CAR_TYPE, car.DAILY_FEE, 
    DATEDIFF(history.END_DATE, history.START_DATE) + 1 AS DURATATION_DAY,
    CASE 
    WHEN DATEDIFF(history.END_DATE, history.START_DATE) + 1 >= 90 THEN "90일 이상"
    WHEN DATEDIFF(history.END_DATE, history.START_DATE) + 1 >= 30 THEN "30일 이상"
    WHEN DATEDIFF(history.END_DATE, history.START_DATE) + 1 >= 7 THEN "7일 이상"
    ELSE "NONE"
    END AS DURATION_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY history
JOIN CAR_RENTAL_COMPANY_CAR car ON car.CAR_ID = history.CAR_ID
WHERE car.CAR_TYPE = "트럭"
)



SELECT discount.HISTORY_ID, ROUND((discount.DAILY_FEE * discount.DURATATION_DAY) * (100 - IFNULL(plan.DISCOUNT_RATE,0)) /100) AS FEE
FROM DISCOUNT discount
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan 
ON discount.DURATION_TYPE = plan.DURATION_TYPE AND discount.CAR_TYPE = plan.CAR_TYPE
ORDER BY 2 DESC, 1 DESC;



# WHERE car.CAR_TYPE = "트럭"





# SELECT * , TIMEDIFF(history.END_DATE, history.START_DATE) AS DAY, (TIMEDIFF(history.END_DATE, history.START_DATE)/24) * car.DAILY_FEE * (100 - plan.DISCOUNT_RATE) AS FEE
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY history
# JOIN CAR_RENTAL_COMPANY_CAR car ON car.CAR_ID = history.CAR_ID
# JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan ON car.CAR_TYPE = plan.CAR_TYPE
# WHERE car.CAR_TYPE = "트럭"



