-- 코드를 입력하세요
SELECT users.USER_ID, users.NICKNAME, SUM(boards.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER users
JOIN USED_GOODS_BOARD boards ON users.USER_ID = boards.WRITER_ID
WHERE boards.STATUS = 'DONE'
GROUP BY users.USER_ID
HAVING SUM(boards.PRICE) >= 700000
ORDER BY TOTAL_SALES;

