# -- 코드를 작성해주세요
# SELECT info.ITEM_ID, info.ITEM_NAME, info.RARITY
# FROM ITEM_INFO info
# JOIN ITEM_TREE tree
# ON info.ITEM_ID = tree.ITEM_ID
# WHERE tree.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
# ORDER BY info.ITEM_ID DESC;


SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY 
FROM ITEM_INFO AS A
JOIN ITEM_TREE AS B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IN (SELECT ITEM_ID FROM ITEM_INFO WHERE RARITY = 'RARE')
ORDER BY A.ITEM_ID DESC;