# SELECT child.ID, child.GENOTYPE, parent.GENOTYPE AS PARENT_GENOTYPE
# FROM ECOLI_DATA child
# JOIN ECOLI_DATA parent
# ON child.PARENT_ID = parent.ID
# WHERE child.GENOTYPE & parent.GENOTYPE = parent.GENOTYPE
# ORDER BY child.ID ASC;



SELECT c.ID, c.GENOTYPE, p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA p
JOIN ECOLI_DATA c
ON p.ID = c.PARENT_ID
WHERE (p.GENOTYPE & c.GENOTYPE = p.GENOTYPE)
ORDER BY c.ID