# SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
#     ABS(B.MAX_SIZE-A.SIZE_OF_COLONY) AS YEAR_DEV, A.ID 
# FROM ECOLI_DATA A
# LEFT JOIN (
# SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, 
#     YEAR(DIFFERENTIATION_DATE) AS YEAR 
#     FROM ECOLI_DATA A
#     GROUP BY YEAR(DIFFERENTIATION_DATE)) B
#     ON YEAR(A.DIFFERENTIATION_DATE) = B.YEAR
# ORDER BY YEAR ASC, YEAR_DEV ASC;

WITH MaxSizePerYear AS (
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(a.DIFFERENTIATION_DATE) AS YEAR, b.MAX_SIZE - a.SIZE_OF_COLONY AS YEAR_DEV, a.ID
FROM ECOLI_DATA a
JOIN MaxSizePerYear b
ON YEAR(a.DIFFERENTIATION_DATE) = b.YEAR
ORDER BY YEAR, YEAR_DEV;