-- 코드를 입력하세요
SELECT DISTINCT(car.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR car
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history ON car.CAR_ID = history.CAR_ID
WHERE MONTH(history.START_DATE) = 10 AND car.CAR_TYPE = '세단'
ORDER BY car.CAR_ID DESC;