-- 코드를 작성해주세요
# SELECT a.ID, b.FISH_NAME, LENGTH
# FROM FISH_INFO a
# JOIN FISH_NAME_INFO b
# ON a.FISH_TYPE = b.FISH_TYPE
# WHERE a.LENGTH = (SELECT MAX(LENGTH) FROM FISH_INFO WHERE FISH_TYPE = a.FISH_TYPE)
# ORDER BY a.ID ASC;

SELECT i.ID, n.FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO n
ON i.FISH_TYPE = n.FISH_TYPE
WHERE (i.FISH_TYPE, i.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO 
                 GROUP BY FISH_TYPE)
     ORDER BY i.ID ASC;


