SELECT SUM(b.SCORE) AS SCORE, a.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL
FROM HR_EMPLOYEES a
JOIN HR_GRADE b
ON a.EMP_NO = b.EMP_NO
GROUP BY b.YEAR, a.EMP_NO, a.EMP_NAME, a.POSITION, a.EMAIL
ORDER BY SCORE DESC LIMIT 1;

