-- 코드를 입력하세요
SELECT ice.INGREDIENT_TYPE, SUM(half.TOTAL_ORDER) AS TOTAL_ORDER 
FROM FIRST_HALF half
JOIN ICECREAM_INFO ice ON half.FLAVOR = ice.FLAVOR
GROUP BY ice.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;