-- 코드를 작성해주세요
# SELECT depart.DEPT_ID, depart.DEPT_NAME_EN, ROUND(AVG(employ.SAL)) AS AVG_SAL
# FROM HR_DEPARTMENT depart
# JOIN HR_EMPLOYEES employ ON depart.DEPT_ID = employ.DEPT_ID
# GROUP BY depart.DEPT_ID
# ORDER BY ROUND(AVG(employ.SAL)) DESC;


SELECT d.DEPT_ID, d.DEPT_NAME_EN, ROUND(AVG(e.SAL)) AS AVG_SAL
FROM HR_DEPARTMENT d
JOIN HR_EMPLOYEES e
ON e.DEPT_ID = d.DEPT_ID
GROUP BY d.DEPT_ID
ORDER BY AVG_SAL DESC;