-- 코드를 입력하세요
# SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME 
# FROM FOOD_PRODUCT
# WHERE CATEGORY IN ('과자','국','김치','식용유') AND PRICE IN (
#     SELECT MAX(PRICE) FROM FOOD_PRODUCT 
#     GROUP BY CATEGORY
# )
# ORDER BY MAX_PRICE DESC;

SELECT f.CATEGORY, f.PRICE AS MAX_PRICE, f.PRODUCT_NAME
FROM FOOD_PRODUCT f
JOIN (
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY IN ('과자','국','김치','식용유')
    GROUP BY CATEGORY
) m
ON f.CATEGORY = m.CATEGORY AND f.PRICE = m.MAX_PRICE
ORDER BY f.PRICE DESC;
