# WITH frontend AS(
#     SELECT SUM(CODE)
#     FROM SKILLCODES
#     WHERE CATEGORY = 'Front End'
# )


# SELECT CASE 
#     WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') 
#     AND SKILL_CODE & (SELECT * FROM frontend)
#     THEN 'A'
#     WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#') 
#     THEN 'B'
#     WHEN SKILL_CODE & (SELECT * FROM frontend)
#     THEN 'C'
#     END AS GRADE, ID, EMAIL
# FROM DEVELOPERS 
# HAVING GRADE IS NOT NULL
# ORDER BY GRADE, ID;


WITH frontend AS (
    SELECT SUM(CODE)
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
)

SELECT CASE
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python') 
    AND SKILL_CODE & (SELECT * FROM frontend) THEN 'A'
    WHEN SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')  
    THEN 'B'
    WHEN SKILL_CODE & (SELECT * FROM frontend)
    THEN 'C'
    END AS GRADE, ID, EMAIL
FROM DEVELOPERS
HAVING GRADE IS NOT NULL 
ORDER BY GRADE, ID;
